// vue-child/src/components/Pager.vue
<template>
  <div class="Pager">
    <div class="Buttons">
      <button>Page 1</button>
      <button>Page 2</button>
      <button>Page 3</button>
    </div>
  </div>
</template>

<script>
import {computed} from 'vue';

export default {
  name: "Pager",
  setup() {

  }
}
</script>

<style scoped>
  .Pager {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .Pager .Buttons {
    display: flex;
    flex-direction: row;
    justify-content: space-around;
  }

  .Pager button {
    background-color: unset;
    border: 1px solid black;
  }

  .Pager button.active {
    background-color: green;
  }
</style>

// svelte-child/src/components/Pager.svelte
<script>
    import { Route, Link } from 'svelte-routing';
    import Page from './Page.svelte';
</script>

<style>
    .Pager {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .Pager .Buttons {
        display: flex;
        flex-direction: row;
        justify-content: space-around;
    }

    .Pager button {
        background-color: unset;
        border: 1px solid black;
    }

    .Pager button.active {
        background-color: yellow;
    }
</style>

<div class="Pager">
    <div class="Buttons">
        <Link to="/page/1">
            <button>Page 1</button>
        </Link>
    </div>
    <div>
        <Route path="/page/:number" component={ Page } />
    </div>
</div>
